### ISSUE TITLE
Move to fsprojects

### ISSUE THREAD

**Issue by sergey-tihon** [dungpa/Z3Fs#7]
@dungpa what do you think about moving this to fsprojects org?

The project may find a new maintainer there and be updated for the latest Z3 and .NET support.

https://twitter.com/dsymetweets/status/1738900302978339278

**Comment by dungpa** [comment]
@sergey-tihon Done.
See the new repo at https://github.com/fsprojects/Z3Fs.

**Comment by sergey-tihon** [comment]
thank you @dungpa ! (restored you admin access to the repo)

@haf can you please add https://www.nuget.org/profiles/fsprojects to owners of https://www.nuget.org/packages/FsZ3? (if the package is created from this repo)

**Comment by haf** [comment]
It's not; I extended and improved this repo and built it from https://github.com/haf/FsZ3

**Comment by haf** [comment]
Also I don't add fsprojects as owners because the remove me from owners without asking.

**Comment by dsyme** [comment]
@haf Our apologies, that would be against our policy if you were the originator, we may have made a mistake. Can we work with you to rectify it? Which project and package are we talking about?

**Comment by sergey-tihon** [comment]
> It's not; I extended and improved this repo and built it from https://github.com/haf/FsZ3

Thank you for the clarification, I missed somehow that you have a fork.

> Also I don't add fsprojects as owners because the remove me from owners without asking.

This should never happen with the original project owner. Sorry one more time, if it happened. Please share the project/package name so we may take a look and fix the mistake.

Closing this issue, because the move is done.
Happy New Year everyone!
